### ISSUE TITLE
how can we display that large image on top rather than below

### ISSUE THREAD

**Issue by Dhamu143** [webismymind/wimmviewer#1]
i want to display that large image on top of that sliders.

**Comment by Nyl000** [comment]
Hi, I added a property allowing to to that. 
Please see the example file on the last release.

https://github.com/webismymind/wimmviewer/releases/tag/1.4
https://github.com/webismymind/wimmviewer/commit/17a83467a1f61f8762a366a35dc3d07993a65f25
